name: build2zip
on:
  - push
  - pull_request

jobs:
  build2zip:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
          run_install: false
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
      - name: build and zip
        run: |
          pnpm install
          pnpm build -b edge
          pnpm build -b chrome
      - name: upload chrome
        uses: actions/upload-artifact@v4
        with:
          name: sci-fig-downloader-chrome
          path: .output/chrome-mv3
      - name: upload edge
        uses: actions/upload-artifact@v4
        with:
          name: sci-fig-downloader-chrome
          path: .output/edge-mv3