name: build2zip
on:
  - push
  - pull_request

jobs:
  build2zip:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
          run_install: false
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
      - name: build and zip
        run: |
          pnpm install
          pnpm build
      - name: Read version of package.json
        uses: xile611/read-package-version-action@v2.1
        id: package-version
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: sci-fig-downloader-${{ steps.package-version.outcome.current_version }}
          path: dist/